### PR TITLE
#130 email signups

### PR DESCRIPTION
**Pull request by pdvorchik**
This references #130 but doesn't close it quite yet.

@meganrm I tried to get https://actionnetwork.org/docs/v2/unauthenticated-post/ to work with the url on https://actionnetwork.org/docs/v2/person_signup_helper but no dice -- so I think we need to make our own form on actionnetwork?  Once we setup that we need to update the url this PR is posting to.

I've cleaned up the UX a bit and thought a bit more about how we want to show the signup form.  I'm wary of removing the logo on search to make space for the signup form.  Instead I think we should just bump the MoC cards down a bit and stick it in between.  That way the UX stays consistent and we keep our branding in a prime location.

This PR includes: 
- Validation for all fields, including email and zip
- Searching for townhalls will automatically enter the zip and districts
- We're saving all of the districts a zip has, after thinking more I don't think most people know what district they live in
- Once you submit the form it's saved in localstorage, and so should never appear again

Screens:
image

image

image

image

image

image

### CODE REVIEW

**Comment by DylanMoriarty** [comment]
@pdvorchik I'm a bit iffy on some of the elements style. In general, if we're creating a new section we should really give it room to breathe. The logo looks _really_ tight when it's blown up.

- Separating the 'find a town hall' button to below the lookup box makes it feel like it should do something regardless of there being an input. As their functionally tied together, they should be connected.

- Do we need last name? Right now it's a required field.

- 'Opt into partner emails' sounds ominous. We should explain that somewhere and make it apparent here.

- There's another [sign up page](http://localhost:5000/#join) on the site. We should match the styling to some degree between these, and perhaps clarify what people are signing up for, like we do on that page.

- Having this between the map events & the table events breaks the flow for me between those two features. If we shorten the table to maybe the first ten elements, I think this would work well below there.

Really exciting to see all these features come together! We should definitely do some regrouping soon to make the interface better unite em'.

**Comment by pdvorchik** [comment]
@DylanMoriarty Thanks for all the feedback!  

After discussing it with @meganrm I'm reverting the header changes for now and we can readdress them later, maybe in a new branch.

As for the points you raised:

1) Putting the button underneath allows us to make the logo a bit larger (which helps with branding) and makes the two columns better visually balanced.  Otherwise all the emphasis is on the logo and the call to action sort gets lost.  I hear your point though, and perhaps we can address it a different way?  For instance, we could set the button to 75% opacity (or whatever looks good) until they've started to add input to the form?

2) No idea.  Care to weigh in@meganrm @nathanmwilliams?

3) Yeah Nathan suggested "Opt in to updates from progressive partners." and I'll see if I can get that to fit in.

4) Completely agreed about syncing up the styling, but I was leaving that for another PR.  In generally we need to go through and sync up a bunch of styles on the site as there's a lot of stuff that is a bit incongruent.  I think people can get the general gist of what it's for though, signup forms are pretty common.  @meganrm also suggested changing the text to "Stay up to date on events in 92024" after the user does a search, which would nest nicely with what you're saying.

5) Any suggestions about where else to put it?  We want the zip code search and the map to be the first thing people see, but we need to keep any important calls to action above the fold for desktop users.  I'm less concerned about the event table (even after spending so much time with that filter logic ;).  It's cool and all, but it's more useful for researchers than activists.  And most of our users afaik fall into the former category.

**Comment by DylanMoriarty** [comment]
1. Strongly disagree that larger logo = better branding. It's already kinda an issue that we have the THP logo not only twice on the homepage but in two different styles. Really we should just redesign it altogether 😉. 

As for the buttons, I like the red a lot because it's a bright saturated color that really pops on the initial view. The white version doesn't as much because of the similarities to the header & logo. Having the 'Find Townhalls' button have a disabled view would work, but I do think overall it should still be connected in some way.

4. :+1:

**Comment by meganrm** [comment]
I merged this into dev because the map wasn't ready yet. There may be some style changes in here @pdvorchik that you want to save for later though.

**Pull request closed without merging**
