### PR TITLE
Fix/style changes to cards

### PR DESCRIPTION
**Pull request by meganrm**
Changes to cards
1. Added the last updated in a footer, which is nice to see for events that are coming up soon, but my question on this is we have some events that haven't been updated in awhile, does it make things look stale?
2. Formatted the address so that it breaks at the right point 
3. Changed the box around the address to a line
4. moved links to the lower right hand corner. 

screenshot 2017-11-09 10 14 36
screenshot 2017-11-09 10 14 55

### CODE REVIEW

**Comment by nathanmwilliams** [comment]
**Added the last updated in a footer, which is nice to see for events that are coming up soon, but my question on this is we have some events that haven't been updated in awhile, does it make things look stale?**

I assume these are ongoing events (regular office hours)? Maybe we lose the "last updated" for those types of events?

Other changes look solid. A couple questions:

-Do we want the Notes to be above the address? In the examples you used it works but occasionally the Notes can be very long (such as a long list of additional speakers or co-host organizations). 

-The bar color is still connected to Party and the little icon/color is connected to the event type on our map? I'm wondering if there is a cleaner way to convey these (rather than blue on blue, with each blue signifying something different).

**Comment by meganrm** [comment]
yeah we can switch notes and address.
The headers are only connected to the type of event. Blue is for in person, purple for staff etc

**Comment by nathanmwilliams** [comment]
So the entire header color (including icon) are representing the same thing with two different color shades? We may have already discussed this but I wonder if it's a bit confusing (assuming that one is representing party).

**Comment by meganrm** [comment]
yeah that's right. There's nothing that indicates party by color anymore.

**Comment by pdvorchik** [comment]
Love the links on the bottom right!

May I make a suggestion about the header? Right now the MOC's name seems understated and the event type icon isn't very grokable.  What if we made them columns instead?  Something like: 
nukgwsb

**Comment by meganrm** [comment]
yeah! do you have this styled already or did you do in with screen grabs? if you have the style can you just push it to this branch?

**Comment by pdvorchik** [comment]
Screen grabs I'm afraid

**Pull request merged**
