### PR TITLE
#287 state dropdown

### LINKED ISSUE #287: Add top bar State drop down
Horrifically rough sketch here.
topbar

### PR DESCRIPTION
**Pull request by pdvorchik**
This closes #287 and cleans up the mobile nav menu while we're at it.

### CODE REVIEW

**Comment by meganrm** [comment]
This is great. Two suggestions: I think this should go right after the icon, @nathanmwilliams? I also don't like the gray background on the button, I don't mind the outline but I think the selected/focus state should be the same as the dropdowns on the table.

**Comment by nathanmwilliams** [comment]
By "after the icon" do you mean on the far left hand side between our logo and "About"? I don't have a strong preference here. Though I feel like people's eyes are generally pulled to the Zip Search so having the new State Leg option over there feels intuitive. 

Re: gray background, as currently constructed is it always gray or only when selected/pressed? If the latter, I'm fine with that personally. If the former, agree that it should be white.

Agree on making the drop down for State Leg and drop down for the main table consistent.

**Comment by pdvorchik** [comment]
It should just be grey when you click it -- not normally.   I like changing the background color as it's confirmation of user action, but I do see your point about keeping the UX consistent.  Easy enough to change.

I'll try moving it directly to the right of the icon and see how it looks.   Could be kinda cool as it would work well from a natural language perspective: "Town Hall Project Arizona" etc.  

Will try and change things this weekend.

**Comment by pdvorchik** [comment]
@meganrm updated!

**Pull request merged**
