### PR TITLE
75 Add notes div and collapse logic with basic styling

### LINKED ISSUE #75: For new card layout on home page, can we add a "notes" button
Not intuitive that clicking on the event should give you notes. Maybe just under the Town Hall (etc.) oval?

### PR DESCRIPTION
**Pull request by pdvorchik**
This closes #75.  Nice easy fix!

### CODE REVIEW

**Comment by pdvorchik** [comment]
Thanks for the feedback.  I'll try to hit it tonight or friday.

**Comment by pdvorchik** [comment]
@meganrm Updated.  Mind taking a look when you have a sec?

**Comment by meganrm** [comment]
Looks good, but I think the hover effect and pointer should have the same behavior. So only hover color on clickable items.

**Comment by pdvorchik** [comment]
Sure, updated :)

**Pull request merged**
