### PR TITLE
Feature/mb map table

### PR DESCRIPTION
**Pull request by meganrm**
- Hooked up the table again. 
- Reconnected the event handler object, and removed redundant code (although there are still some unneeded functions)
- I moved things from mapView.js that made more sense in eventView.js (general view that isn't the map) and TownHall.js (changing the townhall object and underlying data)
- Named some of the anonymous functions in mapView so they can be called from other places in the code
- When you search by zip and it returns more than one district the map will focus to a merge of both districts. 
- If a tele town hall is being held by a house member, I put the marker in the district instead of centered in the state. 
- Markers are jittered a little so they're not directly on top of each other if they are in the same location. 
- Changed data load to a listen for new data instead of a 'once' call. 
- hooked up the query param for zipcode, and made one for search by district.
- got rid of the 'x' out button, I had a few people use the page around work, and people mostly found it confusing. 
## Still needed (after these are done, I think we can deploy this, but other people should check it out too): 

- [x] Expand the bounding box for the map focus to include senate events
- [x] For DC and at large districts: Standardize them so they are all '00' codes to match our database, and only display the state in the text readout. 
- [x] Make the legend responsive, probably inline the list and pin it to the top or the bottom of the map for both small screens and when the map is in the half view.

### CODE REVIEW

**Comment by DylanMoriarty** [comment]
@meganrm I'm having difficulty replicating the zoom bug as described. Is there a certain view/browser your using to get it?

**Comment by meganrm** [comment]
I am too, which is a little weird, I'll let you know if I find it again.

**Comment by DylanMoriarty** [comment]
@meganrm all three blockers have been addressed. It'd be great if you or @pdvorchik could check out the work to make sure everything's addressed, and if we're good let's set the merger train off from the station.

:shipit:  🚋 🚋 🚋

**Comment by meganrm** [comment]
@DylanMoriarty awesome! thanks for taking care of those so quickly. I'll take a look at this tomorrow and I think we can have all of this work in the development branch tomorrow. Right now I have the PR pointing to your branch but it may be easiest to just edit this one to have it merge back into dev directly.

**Pull request merged**
